### ISSUE TITLE
The relax result didn't match with IOPTCELL

### ISSUE THREAD

**Issue by LavendaRaphael** [Chengcheng-Xiao/VASP_OPT_AXIS#2]
INCAR
```
 IOPTCELL =  0 0 0 0 0 0 1 1 1   # 0=fix, 1=relax
```
POSCAR
```
    13.01404700     0.00000000     0.00000000
    -0.01455819    13.03092687     0.00000000
    -0.02255364     0.02440978    26.06190081
```
CONTCAR
```
    13.0140469999999997    0.0000000000000000   -0.0002321326061507
    -0.0145581900000000   13.0309268700000001   -0.0001160023254931
    -0.0225536400000000    0.0244097800000000   26.0624166033657794
```

As shown above, when I fixed "zx zy zz", the cell relax "xz yz zz".

**Comment by LavendaRaphael** [comment]
Another test:
#============================================
#--------------------------------------[INCAR]
```
 IOPTCELL =  0 0 1 0 0 1 0 0 1   # 0=fix, 1=relax
```
#--------------------------------------[POSCAR]
```
    13.01404700     0.00000000     0.00000000
    -0.01455819    13.03092687     0.00000000
    -0.02255364     0.02440978    26.06190081
```
#--------------------------------------[CONTCAR]
```
    13.0140469999999997    0.0000000000000000    0.0000000000000000
    -0.0145581900000000   13.0309268700000001    0.0000000000000000
    -0.0230185066516839    0.0241772553410532   26.0624164201584421
```
#============================================

**Comment by Chengcheng-Xiao** [comment]
Sorry for the late reply.

Please make sure you have used the correct patch file. For `IOPTCELL` to work, `cell_relax_finner.patch` should be used.

If compiled correctly, you'll see Constraining cell: x  x  x | x  x  x | x  x  x in vasp's standard output.

**Comment by LavendaRaphael** [comment]
> Sorry for the late reply.
> 
> Please make sure you have used the correct patch file. For `IOPTCELL` to work, `cell_relax_finner.patch` should be used.
> 
> If compiled correctly, you'll see Constraining cell: x x x | x x x | x x x in vasp's standard output.

Of course, I can see `Constraining cell:  0  0  1  |  0  0  1  |  0  0  1`  in the standard output of the second test. Unfortunately, the test data has been deleted, and only the second test data is retained. According to testing, it is clear that the revised version was indeed effective.
What I want to point out is that I did not directly use cell_relax_finner.patch at the time, because I was using vasp.6.2.0 and the patch file was configured for vasp.5.4.4. Therefore, I directly modified the source file `src/constr_cell_relax.F` and `src/main.F` based on your patch file.

**Comment by Chengcheng-Xiao** [comment]
Okay, I don't have access to 6.2.0 at the moment and I'm not sure if you did something wrong with your rewrite.
Can you send me your "second" test's inputs so that I can investigate further?

**Comment by LavendaRaphael** [comment]
> Okay, I don't have access to 6.2.0 at the moment and I'm not sure if you did something wrong with your rewrite.
> Can you send me your "second" test's inputs so that I can investigate further?

I have attached all the related files here. Thanks a lot!
[cellopt.zip](https://github.com/Chengcheng-Xiao/VASP_OPT_AXIS/files/6418866/cellopt.zip)

**Comment by Chengcheng-Xiao** [comment]
Okay, I see that you have set `IOPTCELL` to `0 0 1 0 0 1 0 0 1`. 
For this setting, this is actually the desired behaviour, let me explain:

What `IOPTCELL` actually does is fixing the corresponding stress tensor elements. 
The lattice vectors are updated after each scf loop using the following formula (you can the following in `dyna.F`):

```
      DO J=1,3
         DO I=1,3
            A(I,J)=AC(I,J)
            DO K=1,3
               A(I,J)=A(I,J) + SSIF(I,K)*AC(K,J)*STEP
            ENDDO
         ENDDO
      ENDDO
```

Where `SSIF` is the (scaled) stress tensor, `A` is the lattice vector matrix and `STEP` is the step size.

You see here, `A` is updated by adding `matmul(SSIF, A(un modified))` to itself. 

This is the reason why setting stress tensor elements cannot enable precise control of each lattice matrix element.

I realized that my `readme.md`  is a bit confusing. Sorry about that.🙁

In the meantime, direct fixing of the lattice elements should be pretty straightforward (at the expanse of some numerical instabilities, more tests needed...) and I'll add this functionality to the patch in the following days.

Thank you for raising this issue!

**Comment by Chengcheng-Xiao** [comment]
@LavendaRaphael 

I've updated the repo. The direct fixing of the lattice elements is now available. Please read the new `readme.md` file on how to use it.

Oh, and this patch works with v6.2.0 too.

---
I've tested your case and here's the difference between the relaxed structure and the unrelaxed one:
```
CONTCAR                 	                      	      |	POSCAR
    1.000000000000000     				      |	1.0
    13.0140469999999997    0.0000000000000000   -0.0013829098 |	    13.01404700     0.00000000     0.00000000
    -0.0145581900000000   13.0309268700000001    0.0001751520 |	    -0.01455819    13.03092687     0.00000000
    -0.0225536400000000    0.0244097800000000   26.0280088421 |	    -0.02255364     0.02440978    26.06190081
   O    Li   La   Zr					      |	  O  Li  La  Zr
   192   112    48    32				      |	  192  112  48  32
Direct								Direct
  0.9623251870967183  0.0536835575358617  0.0729278748445782  |	     0.96237800     0.05377400     0.07288300
```

Note that I've changed `ENCUT` to 500 for quicker convergence.

My input and output can be found [2021-05-07-fix_relax.tar.gz](https://github.com/Chengcheng-Xiao/VASP_OPT_AXIS/files/6440667/2021-05-07-fix_relax.tar.gz).

**Comment by LavendaRaphael** [comment]
Thanks for the test. I will get a clearer understanding of the functionality of your patch from the updated README file. Your code is very useful for complex non-orthogonal units. Maybe next time I should try to build orthogonal units, which will make things easier.
Can your patch file be used directly for 6.2.0? Does that mean I can execute `patch -p0 < cell_relax.patch`? it's great! Because I noticed that "5.4.4" is written in the patch file, and I am not familiar with the patch language, I was a little worried about it before.
There are some writing errors in the README file: `stress_relax.patch` does not match the code file name `fixing_stress_tensor/cell_relax.patch`.

**Comment by Chengcheng-Xiao** [comment]
Yes, it can be used directly on v6.2.0, the `patch` command should be able to automatically find the offset and then patch it (note that I'm using patch version 2.7.1). 

The typo in the `readme.md` has been fixed, thanks for pointing it out. 🤟
