### ISSUE TITLE
Does the latest VASP version still not support such a feature?

### ISSUE THREAD

**Issue by hongyi-zhao** [Chengcheng-Xiao/VASP_OPT_AXIS#3]
It seems that this project was updated a long time ago. Does the latest VASP version still not support such a feature?

Regards,
Zhao

**Comment by Chengcheng-Xiao** [comment]
As far as I know, no. 👀

**Comment by hongyi-zhao** [comment]
1. I confirmed your conclusion [here](https://www.vasp.at/forum/viewtopic.php?f=4&t=19086):

![image](https://github.com/Chengcheng-Xiao/VASP_OPT_AXIS/assets/11155854/492249f9-a862-4903-b713-0979746ec649)

2. I noticed the following information in the patches of this repository:

```shell
werner@X10DAi:~/Public/repo/github.com/Chengcheng-Xiao/VASP_OPT_AXIS.git$ ug vasp |grep diff
fixing_stress_tensor/stress_relax_finner.patch:diff --color -bruN src/constr_cell_relax.F ../vasp.5.4.4_mod/src/constr_cell_relax.F
fixing_stress_tensor/stress_relax_finner.patch:diff --color -bruN src/main.F ../vasp.5.4.4_mod/src/main.F
fixing_lattice_matrix/cell_relax.patch:diff -ru src/constr_cell_relax.F ../../vasp.5.4.4/src/constr_cell_relax.F
fixing_lattice_matrix/cell_relax.patch:diff -ru src/dyna.F ../../vasp.5.4.4/src/dyna.F
fixing_lattice_matrix/cell_relax.patch:diff -ru src/main.F ../../vasp.5.4.4/src/main.F
```
So, I am not sure if these patches are only applicable to VASP.5.4.4.

Regards,
Zhao

**Comment by Chengcheng-Xiao** [comment]
I cannot confirm that these patches will work on newer versions of VASP and I don't plan on testing it myself (at least not in the near future). However, if you do decide to test it, and (if it's not working properly) managed to tweak the code and get it working. I am happy to accept a pull request. 😉

**Comment by hongyi-zhao** [comment]
There are no benchmark test examples provided in this patch. Therefore, it is difficult to verify the correctness of applying/adjusting them to other versions.

Anyway, one of my students have tried to use your patch with vasp.6.3.0:

![image](https://github.com/Chengcheng-Xiao/VASP_OPT_AXIS/assets/11155854/f1771633-9e00-4ec5-a818-103a2349e0c0)

**Comment by Chengcheng-Xiao** [comment]
Cool, I'll whip up some tests and see what I can do with the newer versions when I've time... Thanks for bringing it up tho. 🤟
