### ISSUE TITLE
How to recompile VASP？

### ISSUE THREAD

**Issue by sayeneBB** [Chengcheng-Xiao/VASP_OPT_AXIS#4]
Hi
  im a freshman in DFT caculattion. The terminal output a constrant_cell_relax.F.rej data after inputting "patch -p0 < stress_relax_finner.patch" code. seems like it does not work. And then i try to run a relax task. it failed with "LAPACK: Routine ZPOTRF failed 1 1 1".
  Is that the problem that i had not recompiled the VASP? If so , How should I recompile it?

**Comment by Chengcheng-Xiao** [comment]
This sounds like you are using an incompatible version of VASP. 
Can you make sure you are patching VASP v5.4.4 (which was the version that this patch was tested on)?

**Comment by sayeneBB** [comment]
你好，肖博士：
  我的vasp版本确实是V5.4.4。我已经确定了是还没有重新编译VASP的问题。我将会学习如何编译VASP。谢谢您的解答
